### ISSUE TITLE
Software paper revisions

### ISSUE THREAD

**Issue by kellieotto** [nvihrs14/tcherry#4]
This issue is part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1480) for `tcherry`.

**Statement of need:** I feel that the paper is unclear on A) what kind of problem the software solves (e.g. finding relationships between variables in some certain kind of data) and B) who the audience for this package is (e.g. biologists?). Please clarify these points.

**References:** not all citations have a corresponding DOI. Please add the DOI to every reference that has has one.

**Proofread:** once you have revised the content, please check the grammar for verb tense. I am happy to help with this if you'd like!

**Comment by kellieotto** [comment]
Very minor revisions:

To do this _exact_ --> To do this _exactly_
This is in most cases _to_ time-consuming --> _too_ time-consuming
solve _klassification_ problems with categorical variables --> _classification_

**Comment by katrinekirkeby** [comment]
I have now fixed the revisions
