### ISSUE TITLE
Add a contributing.md file so others know how to contribute

### ISSUE THREAD

**Issue by dhhagan** [nvihrs14/tcherry#9]
If possible, please add a `contributing.md` file so that others know how to contribute. Details can be found [here](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) and an [example here](https://gist.github.com/PurpleBooth/b24679402957c63ec426).

**Comment by nvihrs14** [comment]
Thank you for this advice. I have now added a contributing.md file.
